apiVersion: apps/v1
kind: Deployment
metadata: 
  name: vote-deployment
  labels:
    name: vote-deployment
    app: vote
spec:
  selector:
    matchLabels: 
      name: vote-deployment
      app: vote
  
  template:
    metadata:
      name: vote-deployment
      labels: 
        name: vote-deployment
        app: vote
    
    spec:
      containers:
        - name: vote-deployment
          image: kodekloud/examplevotingapp_vote:before
          resources:
          ports:
            - containerPort: 80
